/**
 * ImagePro Studio — Social Media & Marketing Templates Catalog
 */

export interface DesignTemplatePreset {
  id: string;
  nameAr: string;
  nameEn: string;
  category: "social" | "marketing" | "print" | "ecommerce" | "presentations";
  width: number;
  height: number;
  icon: string;
  aspect: string;
  descriptionAr: string;
  descriptionEn: string;
}

export const DESIGN_TEMPLATES: DesignTemplatePreset[] = [
  {
    id: "insta-square",
    nameAr: "منشور إنستغرام مربع",
    nameEn: "Instagram Post",
    category: "social",
    width: 1080,
    height: 1080,
    icon: "📸",
    aspect: "1:1",
    descriptionAr: "المنشور المربع القياسي لإنستغرام وفيسبوك (1080×1080)",
    descriptionEn: "Standard square social post (1080×1080)",
  },
  {
    id: "story-vertical",
    nameAr: "قصة إنستغرام / تيك توك",
    nameEn: "Story / TikTok / Reel",
    category: "social",
    width: 1080,
    height: 1920,
    icon: "📱",
    aspect: "9:16",
    descriptionAr: "فيديو وقصة رأسية للشاشات الذكية (1080×1920)",
    descriptionEn: "Vertical 9:16 mobile story & reels format (1080×1920)",
  },
  {
    id: "ecommerce-banner",
    nameAr: "إعلان تجاري لمنتج",
    nameEn: "E-Commerce Product Banner",
    category: "marketing",
    width: 1200,
    height: 628,
    icon: "🛍️",
    aspect: "1.91:1",
    descriptionAr: "إعلانات جوجل وفيسبوك التجارية لترويج المنتجات (1200×628)",
    descriptionEn: "High-conversion product ad banner (1200×628)",
  },
  {
    id: "youtube-thumb",
    nameAr: "غلاف فيديو يوتيوب",
    nameEn: "YouTube Thumbnail",
    category: "social",
    width: 1280,
    height: 720,
    icon: "🎬",
    aspect: "16:9",
    descriptionAr: "صورة مصغرة عالية الدقة لفيديوهات يوتيوب (1280×720)",
    descriptionEn: "High-definition video thumbnail (1280×720)",
  },
  {
    id: "header-cover",
    nameAr: "غلاف لينكد إن / فيسبوك",
    nameEn: "Platform Header Cover",
    category: "social",
    width: 1920,
    height: 1080,
    icon: "💼",
    aspect: "16:9",
    descriptionAr: "بانر رأسي للملفات الشخصية وصفحات الشركات (1920×1080)",
    descriptionEn: "Wide header banner for professional pages (1920×1080)",
  },
  {
    id: "business-card",
    nameAr: "بطاقة أعمال شخصية",
    nameEn: "Business Card",
    category: "print",
    width: 1050,
    height: 600,
    icon: "💳",
    aspect: "1.75:1",
    descriptionAr: "بطاقة تعريف وهوية شخصية تجارية (1050×600)",
    descriptionEn: "Standard digital & print business card (1050×600)",
  },
  {
    id: "fb-post",
    nameAr: "منشور فيسبوك قياسي",
    nameEn: "Facebook Feed Post",
    category: "social",
    width: 1200,
    height: 630,
    icon: "📘",
    aspect: "1.91:1",
    descriptionAr: "القياس الأنسب لمشاركات فيسبوك ذات التفاعل العالي (1200×630)",
    descriptionEn: "Standard landscape Facebook timeline post (1200×630)",
  },
  {
    id: "linkedin-banner",
    nameAr: "غلاف لينكد إن الاحترافي",
    nameEn: "LinkedIn Company Banner",
    category: "social",
    width: 1584,
    height: 396,
    icon: "💼",
    aspect: "4:1",
    descriptionAr: "غلاف الحساب والشركات في شبكة لينكد إن (1584×396)",
    descriptionEn: "Official corporate banner for LinkedIn (1584×396)",
  },
  {
    id: "pres-16-9",
    nameAr: "عرض تقديمي عريض (16:9)",
    nameEn: "Presentation Slide (16:9)",
    category: "presentations",
    width: 1920,
    height: 1080,
    icon: "📊",
    aspect: "16:9",
    descriptionAr: "شريحة عرض عريض عالي الدقة للمؤتمرات والشركات (1920×1080)",
    descriptionEn: "Full HD presentation slide deck (1920×1080)",
  },
  {
    id: "poster-a3",
    nameAr: "ملصق وبوستر إعلاني (A3)",
    nameEn: "Event Poster (A3)",
    category: "print",
    width: 1414,
    height: 2000,
    icon: "🖼️",
    aspect: "1:1.41",
    descriptionAr: "بوستر إعلاني وطباعي قياسي للمعارض والفعاليات (1414×2000)",
    descriptionEn: "Commercial vertical poster for print and displays (1414×2000)",
  },
  {
    id: "flyer-a4",
    nameAr: "منشور وفلاير ترويجي (A4)",
    nameEn: "Promotional Flyer (A4)",
    category: "print",
    width: 1240,
    height: 1754,
    icon: "📰",
    aspect: "1:1.41",
    descriptionAr: "نشرة ترويجية إعلانية بحجم ورقة A4 القياسية (1240×1754)",
    descriptionEn: "Standard A4 marketing flyer and leaflet (1240×1754)",
  },
  {
    id: "cv-resume",
    nameAr: "سيرة ذاتية احترافية (CV)",
    nameEn: "Professional CV / Resume",
    category: "print",
    width: 1200,
    height: 1700,
    icon: "📄",
    aspect: "1:1.41",
    descriptionAr: "تنسيق أنيق لسيرة ذاتية تجذب مسؤولي التوظيف (1200×1700)",
    descriptionEn: "Modern executive curriculum vitae layout (1200×1700)",
  },
  {
    id: "invitation-card",
    nameAr: "بطاقة دعوة فاخرة",
    nameEn: "Luxury Invitation Card",
    category: "print",
    width: 1200,
    height: 1680,
    icon: "💌",
    aspect: "5:7",
    descriptionAr: "دعوة رسمية أو شخصية للمناسبات والأفراح والندوات (1200×1680)",
    descriptionEn: "Elegant event invitation card format (1200×1680)",
  },
  {
    id: "ecom-square",
    nameAr: "صورة منتج متجر إلكتروني",
    nameEn: "E-Commerce Square Product",
    category: "ecommerce",
    width: 1200,
    height: 1200,
    icon: "🛍️",
    aspect: "1:1",
    descriptionAr: "عرض واضح ونقي للمنتجات في شوبيفاي وأمازون وسلة (1200×1200)",
    descriptionEn: "High-resolution store catalog product tile (1200×1200)",
  },
  {
    id: "twitter-header",
    nameAr: "ترويسة حساب تويتر / X",
    nameEn: "X / Twitter Header",
    category: "social",
    width: 1500,
    height: 500,
    icon: "🐦",
    aspect: "3:1",
    descriptionAr: "الغلاف العلوي لملفات إكس وتويتر الرسمية (1500×500)",
    descriptionEn: "Standard header banner for Twitter & X profiles (1500×500)",
  },
];
